name: core
description: Core do sistema QClass
version: 0.0.1

environment:
  sdk: ^3.2.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
     
  # navegação
  flutter_modular: ^6.3.4
  
  # utilidades
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.1
  meta: ^1.11.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
