name: qclass_p
description: "Projeto do QClass prático utilizando nova arquitetura"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # design_system_qclass:
  #   git: 
  #     url: git@github.com:bielCoxxta/design_system.git
  #     ref: developer  

  design_system_qclass:
    path: ../design_system
  core:
    path: ../core

  auth:
    path: ../auth    
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.13.1




flutter:
  uses-material-design: true

  assets:
    - .environment/
    - assets/

flutter_icons:
  adaptive_icon_foreground: "assets/logos/launch_icons/foreground_large.png"
  adaptive_icon_background: "#1A2131"
  remove_alpha_ios: true
  image_path: "assets/logos/launch_icons/launch_icon.png"
  android: "ic_launcher"
  ios: true

flavorizr:
  flavors:
    prod:
      app:
        name: "QClass Prático"
      android:
        applicationId: "com.quadritech.qclassP" 
        icon: "assets/logos/launch_icons/launch_icon.png"    
        firebase:
            config: ".firebase/prod/google-services.json" 
      ios:
        bundleId: "com.quadritech.qclassP"
        icon: "assets/logos/launch_icons/launch_icon.png"    
        firebase:
            config: ".firebase/prod/GoogleService-Info.plist"



    dev:
      app:
        name: "QClass Prático DEV"
      android:
        applicationId: "com.quadritech.qclassP.dev"
        firebase:
            config: ".firebase/dev/google-services.json"
        icon: "assets/logos/launch_icons/launch_icon_dev.png"     
      ios:
        bundleId: "com.quadritech.qclassP.dev"
        firebase:
            config: ".firebase/dev/GoogleService-Info.plist"
        icon: "assets/logos/launch_icons/launch_icon_dev.png"     


